### ISSUE TITLE
"Waiting for workspace mamba sync..." prevents ComfyUI from starting

### ISSUE THREAD

**Issue by GinIsTheAnswer** [ai-dock/comfyui#11]
I'm on windows and don't have mamba installed.

**Comment by robballantyne** [comment]
mamba is inside the container. 
That message prints while your environments are synced to your volume mount before start. This is not an error.

Running locally, you may prefer not to sync the environment so you can pass WORKSPACE_SYNC=false to prevent it.

**Comment by GinIsTheAnswer** [comment]
Thanks. I misunderstood that those would be lost every time I restarted it.

Good luck with the update!
