### ISSUE TITLE
SD3.5 (comfy 0.2.6)

### ISSUE THREAD

**Issue by shawnrushefsky** [ai-dock/comfyui#116]
Hey, great work on these images. I'm just requesting an updated release for comfy 0.2.6, which has support for sd3.5. Thanks!

**Comment by robballantyne** [comment]
> Hey, great work on these images. I'm just requesting an updated release for comfy 0.2.6, which has support for sd3.5. Thanks!

Built and tagged.  I haven't had chance to test it yet but I'll push it on `latest` tomorrow if it's working properly

**Comment by shawnrushefsky** [comment]
confirmed working, as is the 0.2.7 image.
