### ISSUE TITLE
Disable the automatic models download

### ISSUE THREAD

**Issue by huchukato** [ai-dock/comfyui#125]
As in the the title, I don't want all the sd and svd models, they keep downloading everytime I delete, taking a lot of time and a lot of space, and in the cloud space costs ))
![Screenshot 2024-12-19 alle 06 48 48](https://github.com/user-attachments/assets/f452fd51-8874-43ae-b894-047f36271ad4)

**Comment by robballantyne** [comment]
Please read the documentation
