### ISSUE TITLE
Flux setup not working, provisioning script doesn't get acknowledged, HF and civitai tokens are ignored; even the default template is broken

### ISSUE THREAD

**Issue by Norby123** [ai-dock/comfyui#126]
I'm very new to vast.ai, and I spent the whole other day trying to make comfyui-Flux work on vast.ai. I spent hours, and burnt unnecessary credits, only to come to the conclusion that it's not working at all. I made my own custom provisioning script, hoping that will fix my issue, used my own json workflow, models from my own HF repository, clips, unets, loras, but no. Nothing gets downloaded and configured. Well, the base  ComfyUI *does* get downloaded, but nothing else, not the Flux dev model, not even the Schnell model (which should be accesible without registration and api token), but not even the default comfy SD1.5 model.
When I tried to `wget` different models, I got an `401 Unauthorized   Authentication Failed.` error.

I posted on Reddit, wondering if I'm doing something wrong, but another user confirmed that the problem is with the default setup.

[https://www.reddit.com/r/StableDiffusion/comments/1hm5xh3/unable_to_set_up_vastai_what_am_i_doing_wrong/
](https://www.reddit.com/r/StableDiffusion/comments/1hm5xh3/unable_to_set_up_vastai_what_am_i_doing_wrong/)

This mainly sucks, because I'm not a programmer, I don't know how to do complicated stuff, but now I can't even use a basic (pretty much default) comfy setup.

Could someone help me out please?

**Comment by robballantyne** [comment]
@Norby123 I'll check this asap - There will be a new template, loosely based on this setup for Vast soon.  Unfortunately the issue with default workflow setting happened after a recent ComfyUI update.

There should not, however, be any issues downloading models.  I tested and found the models downloaded correctly - if your API key doesn't have permissions to access the dev model you may run into issues
