### ISSUE TITLE
Caddy not starting

### ISSUE THREAD

**Issue by GinIsTheAnswer** [ai-dock/comfyui#13]
Hey,

I tried with the latest changes, but caddy doesn't seem to be starting anymore:

`comfyui-supervisor-1  | ==> /var/log/supervisor/comfyui.log <==
comfyui-supervisor-1  | xformers version: 0.0.22
comfyui-supervisor-1  | Set vram state to: HIGH_VRAM
comfyui-supervisor-1  | Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
comfyui-supervisor-1  | VAE dtype: torch.bfloat16
comfyui-supervisor-1  | Using xformers cross attention
comfyui-supervisor-1  | ### Loading: ComfyUI-Manager (V1.6.4)
comfyui-supervisor-1  | ### ComfyUI Revision: 1779 [9b655d4f] | Released on '2023-12-04'
comfyui-supervisor-1  |
comfyui-supervisor-1  | Import times for custom nodes:
comfyui-supervisor-1  |    0.1 seconds: /opt/ComfyUI/custom_nodes/ComfyUI-Manager
comfyui-supervisor-1  |
comfyui-supervisor-1  | Starting server
comfyui-supervisor-1  |
comfyui-supervisor-1  | To see the GUI go to: http://127.0.0.1:18188
comfyui-supervisor-1  | 2023-12-05 17:23:37,376 INFO exited: caddy (exit status 1; not expected)
comfyui-supervisor-1  | 
comfyui-supervisor-1  | ==> /var/log/supervisor/caddy.log <==
comfyui-supervisor-1  | {"level":"info","ts":1701797017.3712878,"msg":"using provided configuration","config_file":"/opt/caddy/etc/Caddyfile","config_adapter":""}
comfyui-supervisor-1  | {"level":"warn","ts":1701797017.3735251,"logger":"http.auto_https","msg":"automatic HTTPS is completely disabled for server","server_name":"srv0"}
comfyui-supervisor-1  | {"level":"warn","ts":1701797017.3736062,"logger":"http.auto_https","msg":"automatic HTTPS is completely disabled for server","server_name":"srv1"}
comfyui-supervisor-1  | {"level":"warn","ts":1701797017.3736272,"logger":"http.auto_https","msg":"automatic HTTPS is completely disabled for server","server_name":"srv2"}
comfyui-supervisor-1  | {"level":"warn","ts":1701797017.373632,"logger":"http.auto_https","msg":"automatic HTTPS is completely disabled for server","server_name":"srv3"}
comfyui-supervisor-1  | Error: loading initial config: loading new config: http app module: start: listening on :11111: listen tcp :11111: bind: address already in use
comfyui-supervisor-1  |
comfyui-supervisor-1  | ==> /var/log/supervisor/supervisor.log <==
comfyui-supervisor-1  | 2023-12-05 17:23:37,376 INFO exited: caddy (exit status 1; not expected)
comfyui-supervisor-1  | 2023-12-05 17:23:38,362 INFO gave up: caddy entered FATAL state, too many start retries too quickly
comfyui-supervisor-1  | 2023-12-05 17:23:38,362 INFO gave up: caddy entered FATAL state, too many start retries too quickly`

None of the ports ([1111:1111⁠][2222:22⁠][53682:53682⁠][8188:8188⁠][8888:8888⁠]) respond. 

Considering the port 11111 bind: address already in use, I guess it's an conflict in the docker itself and not the host system?

**Comment by GinIsTheAnswer** [comment]
comfyui-supervisor-1  | ==> /var/log/supervisor/serviceportal.log <==
comfyui-supervisor-1  | Starting Service Portal...
comfyui-supervisor-1  | INFO:     Started server process [141]
comfyui-supervisor-1  | INFO:     Waiting for application startup.
comfyui-supervisor-1  | INFO:     Application startup complete.
comfyui-supervisor-1  | INFO:     Uvicorn running on http://127.0.0.1:11111 (Press CTRL+C to quit)
comfyui-supervisor-1  |

I guess the Uvicorn is running on that port?

**Comment by GinIsTheAnswer** [comment]
Looks like it happens with WEB_ENABLE_AUTH = false in .env!

**Comment by robballantyne** [comment]
I'll fix it now. Thanks!

**Comment by robballantyne** [comment]
Fixed in base-image. It was a missing newline in the caddy config 🤦‍♂️

Thanks again!
