### ISSUE TITLE
Getting `critical libmamba Could not solve for environment specs` error when run docker compose build

### ISSUE THREAD

**Issue by berkelmas** [ai-dock/comfyui#14]
<img width="970" alt="Screenshot 2023-12-10 at 03 02 26" src="https://github.com/ai-dock/comfyui/assets/42638691/d942b133-1009-4c03-9b48-bb761b893534">

I am using MacOS in m1 chip

**Comment by Daggle24** [comment]
Im having the same issue on windows

**Comment by Daggle24** [comment]
I notice that the python version of the comfyui env is 3.12

I ran this command to see the python version on the layer0 common.sh
![image](https://github.com/ai-dock/comfyui/assets/46680055/752429b6-4621-4ef9-aacb-a184de820827)

and it returns python 3.12.0
![image](https://github.com/ai-dock/comfyui/assets/46680055/bb934b52-6433-460b-9f4d-3ba10e5ccc6e)

**Comment by robballantyne** [comment]
@Daggle24 You're absolutely right.  The compose file is referencing ghcr.io/ai-dock/jupyter-pytorch:latest-cuda - This was fine until recently when I updated the PyTorch images 

Please try rebuilding with the base image set to `ghcr.io/ai-dock/jupyter-pytorch:2.1.1-py3.10-cuda-11.8.0-base-22.04` or `ghcr.io/ai-dock/jupyter-pytorch:2.1.1-py3.10-cuda-12.1.0-base-22.04`

I'll push a sensible default soon (also need to fix xformers)

Sorry I've not been quicker to sort this - I've been away for the last few days

**Comment by berkelmas** [comment]
I have changed the IMAGE_BASE accordingly but now when I deploy the outputted image to runpod, the application does not start. Can you please take a look at the issue below?

https://github.com/ai-dock/comfyui/issues/16
