### ISSUE TITLE
micromamba: command not found

### ISSUE THREAD

**Issue by Daggle24** [ai-dock/comfyui#15]
I cloned the repo on my local machine, changed the enviorement variables and ran docker compose up

But when the server is launched I get this error message:

![image](https://github.com/ai-dock/comfyui/assets/46680055/b46ea75b-2db2-405c-ab51-6903644745df)

**Comment by farlistener** [comment]
Thanky you, I was preparing my report at the same time, I spent part of my week-end to figure out why, upgrade my docker-compose, prune, build and up again and again trying to change some configuration ... and I feel a little bit crazy at the end, a friend of mine saying that his installation works fine (but not build these last days).

Thank you again.

So yes, "micromanba is missing"

**Comment by Daggle24** [comment]
When I run docker build, I get this error message:
![image](https://github.com/ai-dock/comfyui/assets/46680055/5305b8b7-0117-45bc-98e0-26ce6cab16d6)

**Comment by farlistener** [comment]
In my side I've go 

```shell
#7 21.51 warning  libmamba [cuda-nvtx-11.8.86-0] The following files were already present in the environment:
#7 21.51     - LICENSE
```
At the end : 

```shell
/workspace$ ls
ComfyUI  remote  serverless  storage
```
no micromamba directory

and from inside the docker : 

```shell
root@35249cfc753e:/workspace# cd /opt/micromamba/
root@35249cfc753e:/opt/micromamba# ls
'*'
```

**Comment by robballantyne** [comment]
Building fine here and I need more information to help.

What's your architecture?
Build target?
Base image?

Also please provide build logs.

**Comment by Daggle24** [comment]
Im using Windows 11 Pro 64bits  x64
I understand that my build target is Python 3.10 as default (I just cloned the repository as it is)
The only change I made to the docker-compose.yaml was uncommenting these lines:

`  ## For Nvidia GPU's - You probably want to uncomment this
    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - driver: nvidia
    #          count: all
    #          capabilities: [gpu]`
    
    
    
    here are my docker logs:
    `2023-12-10 21:24:31 2023-12-10 20:24:31,472 INFO exited: comfyui (exit status 127; not expected)
2023-12-10 21:24:32 
2023-12-10 21:24:32 ==> /var/log/supervisor/comfyui.log <==
2023-12-10 21:24:32 Starting ComfyUI...
2023-12-10 21:24:32 Starting ComfyUI...
2023-12-10 21:24:32 /opt/ai-dock/bin/supervisor-comfyui.sh: line 77: micromamba: command not found
2023-12-10 21:24:32 
2023-12-10 21:24:32 ==> /var/log/supervisor/supervisor.log <==
2023-12-10 21:24:32 2023-12-10 20:24:31,283 INFO spawned: 'comfyui' with pid 517
2023-12-10 21:24:32 2023-12-10 20:24:31,472 INFO exited: comfyui (exit status 127; not expected)
2023-12-10 21:24:32 2023-12-10 20:24:32,279 INFO gave up: comfyui entered FATAL state, too many start retries too quickly
2023-12-10 21:24:33 2023-12-10 20:24:32,279 INFO gave up: comfyui entered FATAL state, too many start retries too quickly`

**Comment by robballantyne** [comment]
I think one of the base images must have silently failed without breaking the CI. I'll rebuild all bases to hopefully fix this issue

**Comment by anwac** [comment]
I had the same problems. When I went into the workspace on the host and did a 

mkdir environments

it worked better for me. The line

2023-12-10 21:24:12 rsync: [Receiver] mkdir "/workspace/environments/micromamba-comfyui" failed: No such file or directory (2)

gave me that clue. Now if I only could find out how I could use 0.0.0.0 instead of 127.0.0.1  ...

**Comment by anwac** [comment]
actually "Now if I only could find out how I could use 0.0.0.0 instead of 127.0.0.1 ..." was just me being confused. 
I thought the port would be 18188, since there was a message on boot:

To see the GUI go to: http://127.0.0.1:18188

Turns out that, as mentioned elsewhere here, the port that the interface shows up under is 8188. That being the one
expecting the password / username combination. Looking with curl at those ports confused be a bit: I got something on 18188 inside of the docker, but it would not map to the host. Which makes sense, since it probably does not require a pwd. 

This being my second day with docker probably didn't help either ... but now it works ...

**Comment by Daggle24** [comment]
> I had the same problems. When I went into the workspace on the host and did a
> 
> mkdir environments
> 
> it worked better for me. The line
> 
> 2023-12-10 21:24:12 rsync: [Receiver] mkdir "/workspace/environments/micromamba-comfyui" failed: No such file or directory (2)
> 
> gave me that clue. Now if I only could find out how I could use 0.0.0.0 instead of 127.0.0.1 ...

this didn't work for me, the enviroment folder just does this:
![image](https://github.com/ai-dock/comfyui/assets/46680055/daba9eb3-b75d-4833-86d1-714b96eb96ac)

**Comment by robballantyne** [comment]
> > I had the same problems. When I went into the workspace on the host and did a
> > mkdir environments
> > it worked better for me. The line
> > 2023-12-10 21:24:12 rsync: [Receiver] mkdir "/workspace/environments/micromamba-comfyui" failed: No such file or directory (2)
> > gave me that clue. Now if I only could find out how I could use 0.0.0.0 instead of 127.0.0.1 ...
> 
> this didn't work for me, the enviroment folder just does this: ![image](https://private-user-images.githubusercontent.com/46680055/289399935-daba9eb3-b75d-4833-86d1-714b96eb96ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyNzkzOTksIm5iZiI6MTcwMjI3OTA5OSwicGF0aCI6Ii80NjY4MDA1NS8yODkzOTk5MzUtZGFiYTllYjMtYjc1ZC00ODMzLTg2ZDEtNzE0Yjk2ZWI5NmFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDA3MTgxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5ZjlhZTgwYWJjNzA4MmM2MzI3NGRlMjI3Mzg5OGUxMTE3NTkwODdkY2MwNjk5M2RhNGQ4ZmIzMjkzZGM2MzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yhnqnUkxD8U2jPeXtkZi18WEquiF-9ms-HZZhzWd39A)

If you are having trouble with this, please try running with environment variable WORKSPACE_SYNC=false

It's not really necessary to sync the environment locally and I'm considering changing the default behaviour

**Comment by Daggle24** [comment]
> > > I had the same problems. When I went into the workspace on the host and did a
> > > mkdir environments
> > > it worked better for me. The line
> > > 2023-12-10 21:24:12 rsync: [Receiver] mkdir "/workspace/environments/micromamba-comfyui" failed: No such file or directory (2)
> > > gave me that clue. Now if I only could find out how I could use 0.0.0.0 instead of 127.0.0.1 ...
> > 
> > 
> > this didn't work for me, the enviroment folder just does this: ![image](https://private-user-images.githubusercontent.com/46680055/289399935-daba9eb3-b75d-4833-86d1-714b96eb96ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyNzkzOTksIm5iZiI6MTcwMjI3OTA5OSwicGF0aCI6Ii80NjY4MDA1NS8yODkzOTk5MzUtZGFiYTllYjMtYjc1ZC00ODMzLTg2ZDEtNzE0Yjk2ZWI5NmFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDA3MTgxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5ZjlhZTgwYWJjNzA4MmM2MzI3NGRlMjI3Mzg5OGUxMTE3NTkwODdkY2MwNjk5M2RhNGQ4ZmIzMjkzZGM2MzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yhnqnUkxD8U2jPeXtkZi18WEquiF-9ms-HZZhzWd39A)
> 
> If you are having trouble with this, please try running with environment variable WORKSPACE_SYNC=false
> 
> It's not really necessary to sync the environment locally and I'm considering changing the default behaviour

now it's properly working, thanks!
