### ISSUE TITLE
On the creation of a new runpod pod - getting this error 

### ISSUE THREAD

**Issue by ibadmore** [ai-dock/comfyui#2]
<img width="898" alt="Screenshot 2023-10-12 at 1 26 55 PM" src="https://github.com/ai-dock/comfyui/assets/122062584/b5c8ee10-814a-4daa-b0a6-f4a36adf6ff8">

**Comment by ibadmore** [comment]
main.py does exist in the ComfyUI folder

**Comment by robballantyne** [comment]
Thanks. This will be fixed very shortly. There was a fault in the base image which is now resolved so ComfyUI needs a rebuild.

**Comment by ibadmore** [comment]
sweeeet thank you - would i just need to restart to apply the change?

**Comment by robballantyne** [comment]
Unfortunately it needs the image re-pulling as the PyTorch base was missing an important package (and I messed up a copy command)

Just FYI, the issue came about because I updated the init to password protect the ComfyUI instance. Documentation has been updated with the changes

**Comment by robballantyne** [comment]
Closing as tested and working.  

Please let me know if any further issues arise.

Thanks again for your report
