### ISSUE TITLE
FFmpeg should be upgraded to the latest version

### ISSUE THREAD

**Issue by SoaringTiger** [ai-dock/comfyui#20]
When i using "Video Combine" node of  Kosinkadink/ComfyUI-VideoHelperSuite, there is an error:

```
...
subprocess.CalledProcessError: Command '['/opt/micromamba/envs/comfyui/bin/ffmpeg'
...
Exception: An error occured in the ffmpeg subprocess:
Unrecognized option 'crf'
...
```
After I manually upgraded FFmpeg (ffmpeg version 4.4.2-0ubuntu0.22.04.1), it was fine.

**Comment by robballantyne** [comment]
This is being pushed very soon. I've spent some time this weekend updating some scripts to better support ffmpeg versioning.

PyTorch 2.01 will use ffmpeg 4.4 and 2.1.1+ will use ffmpeg 6.x

**Comment by robballantyne** [comment]
New images pushed.
