### ISSUE TITLE
Is XPU_TARGET an environment variable?

### ISSUE THREAD

**Issue by robinjhuang** [ai-dock/comfyui#24]
I see this being used in `init.sh`, however I don't see it in docker-compose.yaml or other places. Where is this being set?

**Comment by robballantyne** [comment]
It's a build time variable set in [ai-dock/base-image](https://github.com/ai-dock/base-image)

It's for determination of the build target and is used in the GitHub actions scripts.

**Comment by robinjhuang** [comment]
Ah I see it in the base image now. Thank you!
