### ISSUE TITLE
ComfyUI commit SHA versioning

### ISSUE THREAD

**Issue by robinjhuang** [ai-dock/comfyui#25]
Would it be possible to include some way to have the comfyUI commit SHA in the build? Currently it seems like the container will clone the latest version of comfyui every time it starts. Which may not be good for all use cases. 

Happy to help contribute a PR after some discussion!

**Comment by robballantyne** [comment]
Absolutely, and this is planned.

In the meantime you can run with `AUTO_UPDATE=false` to avoid pulling the latest version.

You can expect versioning to start within a week or two, I'm just fixing some issues in the base image before I start pinning app versions.

I'll still build auto updating versions on the `latest` tag but versioned images will set `AUTO_UPDATE=false` as a default.

**Comment by robballantyne** [comment]
Latest builds are now tagged with commit SHA. Automatic updates are disabled unless explicitly requested with `AUTO_UPDATE=true`

This change affects all images tagged from now onwards including `latest*`
