### ISSUE TITLE
micromamba environment and ComfyUI both 20+ GB

### ISSUE THREAD

**Issue by ionflow** [ai-dock/comfyui#28]
I've built the latest and pushed to docker hub and run it on runpod with all the models comment out and just 3 nodes. And I'm using a network volume on runpod for all the models I need. I have a 50GB volume and it's 95% full. Both ComfyUI and micromamba are coming in at around 20-25GB. I have my models pulled down from my network volume, so it makes sense that ComfyUI is that big, but does micromamba have to be that big?

<img width="611" alt="Screenshot 2024-01-07 at 3 17 22 PM" src="https://github.com/ai-dock/comfyui/assets/4053903/cdb247cd-87db-497a-895f-4dde44178ccf">

**Comment by robballantyne** [comment]
Runpod has an issue with small file sizes on their volume storage.  You'll notice that the size on /workspace is much larger than the size on /opt before the move. I've raised it but it won't be fixed as it's a known filesystem feature.

If you're building the image with your own models and nodes it's probably not worth syncing at all. You could skip the sync (`WORKSPACE_SYNC=false`) and replace the output directory with a symlink to the workspace.

**Comment by ionflow** [comment]
I see. Will /input, /output, and /models all be synced if I cloud sync from AWS to /workspace/storage? And when you say synced you don't mean duplicated right?

**Comment by robballantyne** [comment]
Models will be if the paths match up to the `mappings.sh` described in the docs but there's no mechanism for linking input/output. You'd have to sync directly into the ComfyUI directory.
