### ISSUE TITLE
Request for help with docker image with gfx803 support

### ISSUE THREAD

**Issue by Ilia01** [ai-dock/comfyui#29]
Hello!

Pre-history:
I'm a newbie into docker and AI stuff, so I haven't managed to do it by myself for 3 days already.
I have a Radeon RX580, which is gfx803, and ROCm dropped it's official support as I know in v.4.0. Yet by data from internet it's still possible to use at least 5.4.3 for sure. And I've used Auto1111 webUI on Linux Mint and it worked. But now I'm on Arch and can't install neither Auto1111, nor ComfyUI. Found webUI docker image for gfx803, and it works, but it's made from the first release of webUI and lacks most of functionality. And also I liked the idea of ComfyUI when I found it out.

Request for help:
Can anyone help to make a docker image with requirements needed for gfx803 support? As it needs torch built with it's flag enabled, while pre-built packages of it are only in .deb files and I wasn't able to build it successfully. Raw ComfyUI w/o docker starts on my PC, but prompts can't be made, as with current ROCm and torch it ends with segmentation fault (same on Auto webUI w/o docker).
With my still very limited amount of knowledge I am unable to make it without help.

Will be very grateful if someone is able to help!

**Comment by robballantyne** [comment]
These images use pre-compiled torch and there is no plan to build from source.

I have had no feedback whatsoever on whether the images work correctly on AMD - I don't have access to any AMD hardware so I have no way to help you, unfortunately.

**Comment by rastarr** [comment]
is it somehow possible to include this - https://github.com/tsl0922/pytorch-gfx803

**Comment by robballantyne** [comment]
Sorry, It's out of scope for this project.

In the future I may consider adding support for legacy equipment but it is unlikely to be any time soon as I have a lot to do first.
