### ISSUE TITLE
New Error

### ISSUE THREAD

**Issue by ibadmore** [ai-dock/comfyui#3]
Hi! Thanks for reviewing these errors. Got a new error today that delays the loading of the pod and of images on ComfyUI. Unsure what caused this.

==> /var/log/supervisor/caddy.error.log <==
{"level":"error","ts":1698128485.8749824,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","upstream":"localhost:18188","duration":0.001717137,"request":{"remote_ip":"100.64.0.21","remote_port":"40104","client_ip":"100.64.0.21","proto":"HTTP/1.1","method":"GET","host":"100.65.13.44:60326","uri":"/lib/litegraph.core.js","headers":{"Remote-User":["{http.reverse_proxy.header.Remote-User}"],"Cdn-Loop":["cloudflare"],"Sec-Fetch-Site":["same-origin"],"Cf-Ray":["81b01d9ebbe82a8f-LAX"],"Referer":["https://dnxk8p80nrvs08-8188.proxy.runpod.net/"],"Cookie":[],"Accept-Encoding":["gzip, br"],"X-Forwarded-For":["100.64.0.21"],"Cf-Connecting-Ip":["2600:1700:6bfc:4750:509a:3876:80bb:bc3f"],"Remote-Groups":["{http.reverse_proxy.header.Remote-Groups}"],"Authorization":[],"User-Agent":["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"],"Remote-Name":["{http.reverse_proxy.header.Remote-Name}"],"Accept":["*/*"],"Sec-Ch-Ua":["\"Chromium\";v=\"118\", \"Google Chrome\";v=\"118\", \"Not=A?Brand\";v=\"99\""],"Sec-Ch-Ua-Mobile":["?0"],"Remote-Email":["{http.reverse_proxy.header.Remote-Email}"],"Cf-Visitor":["{\"scheme\":\"https\"}"],"Cf-Ipcountry":["US"],"Accept-Language":["en-US,en;q=0.9,ja;q=0.8"],"X-Forwarded-Proto":["http"],"X-Forwarded-Host":["100.65.13.44:60326"],"Sec-Ch-Ua-Platform":["\"macOS\""],"Sec-Fetch-Dest":["script"],"Sec-Fetch-Mode":["no-cors"]}},"error":"writing: write tcp 172.24.0.2:8188->100.64.0.21:40104: write: broken pipe"}

**Comment by robballantyne** [comment]
Hi

I'll look into this today. Is it happening on all pods every time you run, or is it an intermittent issue?

**Comment by ibadmore** [comment]
It looks like the error has stopped happening - not exactly sure what was causing it initially. Apologies for the ticket!

**Comment by robballantyne** [comment]
No problem :)
