### ISSUE TITLE
PreviewImage nodes result in copy errors

### ISSUE THREAD

**Issue by PoCTo** [ai-dock/comfyui#31]
When I post a workflow json that has a PreviewImage to the API (via /rp-api/runsync), BaseHandler is unable to copy a file:
```bash
DEBUG  | test-c12c72b8-f825-4c0c-916e-68d62d92296d | run_job return: {'error': "[Errno 2] No such file or directory: '/workspace//ComfyUI/output//ComfyUI_temp_mqplo_00001_.png' -> '/workspace//ComfyUI/output/test-c12c72b8-f825-4c0c-916e-68d62d92296d/ComfyUI_temp_mqplo_00001_.png'"}
```
This is due to the fact that PreviewImage saves the image [to the temp directory](https://github.com/comfyanonymous/ComfyUI/blob/ee2c5fa72d4fc1714576fac7ba64aa5d607303d0/nodes.py#L1442)

It is questionable whether temp images must be returned. I guess it would be great if it can be configured

I propose to not iterate over images with type="temp" for now since otherwise it fails

**Comment by robballantyne** [comment]
I'll add this. I need to handle outputs more effectively because currently it's only looking at standard png but really should cover jpg, mp4 etc

Thanks

**Comment by robballantyne** [comment]
Most recent builds now return all output files of type "output". Temp files are still ignored for now but will be added soon if the workflow creates previews
