### ISSUE TITLE
runpod serverless API result getting volume error 

### ISSUE THREAD

**Issue by hongminpark** [ai-dock/comfyui#36]
Hi :) First, thank you for really great opensource.
I am almost at the last step setting runpod serverless, but getting 
<img width="1141" alt="image" src="https://github.com/ai-dock/comfyui/assets/21957275/b9d0b568-543b-4783-8d39-b5e60edb69ed">
`[Errno 2] No such file or directory: '/runpod-volume//ComfyUI/output//ComfyUI_temp_cprvf_00001_.png' -> '/runpod-volume//ComfyUI/output/5a59a89c-2f46-4df3-b387-98b19ff88777-e1/ComfyUI_temp_cprvf_00001_.png'` this error when I run runpod serverless api. 
- I've built custom image based on this repository, followed [this guide](https://github.com/ai-dock/comfyui?tab=readme-ov-file#building-images), deployed on runpod serverless
- this is my environment setting (hid aws values), <img width="917" alt="image" src="https://github.com/ai-dock/comfyui/assets/21957275/5b7342bf-bd43-4849-a0dd-b416570bf674">
- I used [this format](https://github.com/ai-dock/comfyui/blob/main/build/COPY_ROOT/opt/serverless/docs/example_payloads/raw_text2image.json) as a request 

-----(edited)
I've tried editing `basehandler.py` and rebuild the image
```
    # INPUT_DIR=f"{os.environ.get('WORKSPACE')}/ComfyUI/input/"
    # OUTPUT_DIR=f"{os.environ.get('WORKSPACE')}/ComfyUI/output/"
    INPUT_DIR=f"{os.environ.get('WORKSPACE')}ComfyUI/input"
    OUTPUT_DIR=f"{os.environ.get('WORKSPACE')}ComfyUI/output"
```
then I got `[Errno 2] No such file or directory: '/runpod-volume/ComfyUI/output/ComfyUI_temp_ottah_00001_.png' -> '/runpod-volume/ComfyUI/outpute6f68e40-83a3-472e-b576-b96645e2b852-e1/ComfyUI_temp_ottah_00001_.png'` this error. Do I need initialization of 

Hope I can get help 🙏

**Comment by bkunbargi** [comment]
did you resolve this? Running into the same issue. I added https://github.com/cubiq/ComfyUI_IPAdapter_plus to the init.sh and uncommented the 1.5 and sdxl models in the same file

**Comment by hongminpark** [comment]
@bkunbargi I fixed it by changing `basehandler.py` . https://github.com/hongminpark/comfyui/compare/main...hongminpark:comfyui:custom

```
                    clean_filename = re.sub(r"_temp_[^_]+_", "_", image['filename'])
                    new_path = f"{custom_output_dir}/{clean_filename}"
                    key = f"{self.request_id}/{clean_filename}"
```
You can skip this part. (This is because of my workflow included preview image node, and it makes error)

**Comment by coronell123** [comment]
{
  "delayTime": 5676,
  "error": "[Errno 2] No such file or directory: '/runpod-volume/ComfyUI/output/image_00001_.png' -> '/runpod-volume/ComfyUI/output/ed89dafe-c4cb-4938-95ce-f8256da98203-e1/image_00001_.png'",
  "executionTime": 5743,
  "id": "ed89dafe-c4cb-4938-95ce-f8256da98203-e1",
  "status": "FAILED"
}

i implemented these changes and the paths seem to be correct and i checked the code, still its giving me this error? 
any idea why ?

**Comment by hongminpark** [comment]
> { "delayTime": 5676, "error": "[Errno 2] No such file or directory: '/runpod-volume/ComfyUI/output/image_00001_.png' -> '/runpod-volume/ComfyUI/output/ed89dafe-c4cb-4938-95ce-f8256da98203-e1/image_00001_.png'", "executionTime": 5743, "id": "ed89dafe-c4cb-4938-95ce-f8256da98203-e1", "status": "FAILED" }
> 
> i implemented these changes and the paths seem to be correct and i checked the code, still its giving me this error? any idea why ?

try removing 'preview image' node in your workflow. This solved in my case
