### ISSUE TITLE
How to generate an image programatically?

### ISSUE THREAD

**Issue by janoist1** [ai-dock/comfyui#37]
Given the system is running, and I'm able to generate images with ComfyUI.
I'd like to generate an image programatically:
- with a simple python script
- using an existing workflow
- any web API capabilities ?

I'd like to avoid mixing up things inside the container. What is to be installed or required to at least generate an image with python using the current setup ?
many thanks !

**Comment by janoist1** [comment]
Closing: I've found it out. :)

**Comment by ultimatech-cn** [comment]
> Closing: I've found it out. :)

Hi, I am also find the api method, would you kindly show some sample code?

**Comment by janoist1** [comment]
You need to export your workflow in API format. Next, you can use it and make requests, here's an example: https://github.com/comfyanonymous/ComfyUI/blob/master/script_examples/basic_api_example.py

**Comment by ultimatech-cn** [comment]
Thanks, I have test this example. It run well locally.
But when I deploy comfyUI as pod in runpod, it can not be used directly. I should use RP API instead. 
So far I am failed in invoke the api, still trying to make it work.

**Comment by devingfx** [comment]
@ultimatech-cn  You have to add an undocumented WEB_TOKEN env variable at the docker deployment and then add an `Authorization: Bearer $WEB_TOKEN` in your api requests...
See https://github.com/ai-dock/comfyui/issues/95

**Comment by ultimatech-cn** [comment]
Thanks a lot, I will try this.
