### ISSUE TITLE
ComfyUI starts at port 18188 in a container

### ISSUE THREAD

**Issue by cseander** [ai-dock/comfyui#4]
I'm not sure why, but when I run the container comfyui starts at port 18188 instead of 8188. I have not edited any environment variables, simply just downloaded the image and ran it.

==> /var/log/supervisor/provisioning.log <==
Looking for provisioning.sh...
Not found

==> /var/log/supervisor/redirector.error.log <==
INFO:     Started server process [187]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:11111 (Press CTRL+C to quit)

==> /var/log/supervisor/redirector.log <==
Starting redirector server...

==> /var/log/supervisor/sshd.error.log <==
/root/.ssh/authorized_keys is not a public key file.
Skipping SSH server: No public key

==> /var/log/supervisor/sshd.log <==

==> /var/log/supervisor/supervisor.log <==

==> /var/log/supervisor/sync.log <==
No mount: Mamba environments remain in /opt
Creating symlink from /opt/ComfyUI to /workspace/ComfyUI

==> /var/log/supervisor/comfyui.log <==
Total VRAM 14928 MB, total RAM 15000 MB
xformers version: 0.0.22
Set vram state to: NORMAL_VRAM
Device: cuda:0 Tesla T4 : cudaMallocAsync
VAE dtype: torch.float32
Using xformers cross attention
Starting server

To see the GUI go to: http://127.0.0.1:18188

**Comment by robballantyne** [comment]
Hi

This is the correct behaviour. We use Caddy, a reverse-proxy, to listen on 0.0.0.0 port 8188 and forward requests to port 18188.

This is necessary to implement a username and password for ComfyUI which does not natively have any security.

You should be able to access the container at IP:8188

**Comment by robballantyne** [comment]
No issue.
