### ISSUE TITLE
Not all paths are mapped in comfyui:pytorch-2.2.0-py3.10-cuda-12.1.0-runtime-22.04

### ISSUE THREAD

**Issue by SoaringTiger** [ai-dock/comfyui#44]
I have pulled and tested comfyui:pytorch-2.2.0-py3.10-cuda-12.1.0-runtime-22.04 today. 
I found Not all paths are mapped in mappings.sh. 
Every time the container is restarted, some paths will randomly become unmapped.
For example, this time it is the **_checkpoints_** directory, and the next time it is the _**controlnet**_ directory.

But all will work fine in comfyui:pytorchpytorch-2.1.1-py3.10-cuda-12.1.0-base-22.04

**Comment by robballantyne** [comment]
Thanks for the report

Can you confirm which platform you are running on?  I haven't experienced the same, but some permissions changes have been made in the updated base image which may account for this but I'll need to investigate further

**Comment by robballantyne** [comment]
I've managed to replicate this issue. 

Rebuilding with fix ASAP

**Comment by robballantyne** [comment]
@SoaringTiger New builds have replaced the broken version. Hopefully this fixes the issue for you.

I realised that the symlink manager was missing a condition, so when the symlink already existed (as in the case of a restart vs full teardown and start) it would just delete the symlink and quit - Not exactly what I had in mind.

In my testing, it was all of the mappings that disappeared, however, so I'm prepared to accept that there may also be another issue that I haven't yet caught so please do let me know if I need to look again.

Thanks again for reporting this.

https://github.com/ai-dock/base-image/commit/9efaf7e8aa1701dbae2d835164f67e77018824e5

**Comment by SoaringTiger** [comment]
@robballantyne I have pulled and tested latest image again. The bug of recursive symlinks like https://github.com/ai-dock/comfyui/issues/9#issuecomment-1863971649 appears again.

-----
Platform info:
Docker Engine: 25.0.2
OS: Ubuntu:22.04

**Comment by robballantyne** [comment]
Rebuilt to fix recursive symlinks

**Comment by SoaringTiger** [comment]
Tested, works well 👍
