### ISSUE TITLE
Provisioning permission denied

### ISSUE THREAD

**Issue by KubaBir** [ai-dock/comfyui#48]
When running provisioning i get permission errors:

`ln: failed to create symbolic link '/opt/ComfyUI/models/upscale_models/RealESRGAN_x2.pth': Permission denied`
`ln: failed to create symbolic link '/opt/ComfyUI/models/checkpoints/DreamShaper_8_INPAINTING.inpainting.safetensors': Permission denied`

This is the case for all model types (ckpt, esrgan, vae)

I run the image on runpod gpu cloud. I forked the repo and built the image using `docker compose build` I didnt change the image since it last worked.

 I had no problems until today when I tried to redeploy my pod.
Could this be caused by the recent commits to this repo? I created a separate fork so that shouldn't be the case.

**Comment by KubaBir** [comment]
Thanks for the fast reply

I rebuilt the images after pulling the recent changes and it works as expected now.

Please correct me if im wrong:
The base pytorch images can be updated while the tag stays the same - this can cause some changes on my side when rebuilding even if I dont make any changes in my source.

Am I correct in assuming that I could make a copy of the base images and use that for my build so they stay the same regardless of any updates?

**Comment by robballantyne** [comment]
You are correct. The only way to guarantee that no changes will creep in is to freeze the base image as you suggested.
