### ISSUE TITLE
broken access ssh

### ISSUE THREAD

**Issue by pvp-by** [ai-dock/comfyui#50]
```
024-02-29T07:51:19.551713395Z cp: not writing through dangling symlink '/workspace/home/user/.ssh'
2024-02-29T07:51:19.559099834Z chown: changing ownership of '/workspace/home/user/.ssh': Operation not permitted
2024-02-29T07:51:19.566694095Z chmod: cannot access '/workspace/home/user/.ssh/authorized_keys': No such file or directory
```
I have pubkey configured in runpod, but it won't let me into ssh with a response: 
The public key was working a day ago, there was no need to change or affect it in any way (after startup, there is a correct authorized_keys file inside the container).

![image](https://github.com/ai-dock/comfyui/assets/10133995/e36eed2c-f2cb-4daa-bd5b-ba2c21a0805e)
I don't know what log to look at for this situation.

I tested it on 
comfyui:latest 
comfyui:latest-cuda 
webui:latest

same error, and problems with ssh access.
Only webssh from runpod works , but only 1 time, after restart container `Connection Closed`.

**Comment by robballantyne** [comment]
I couldn't replicate issue for 'root' user but 'user' user was broken.

New builds will be ready soon

**Comment by robballantyne** [comment]
New builds have been pushed. Hopefully this resolves the issue for you. I couldn't replicate the problem so if you get chance please could you confirm working.
