### ISSUE TITLE
[Feature request] small docker image for workspace_sync=true

### ISSUE THREAD

**Issue by pvp-by** [ai-dock/comfyui#57]
My clients complain about long loading times, and I'm a bit surprised myself. Why do I have to download a full image including all dependencies and software every time I run it, if I have 90% of what I need already in my workspace (the biggest packages - torch, models, etc.)?

if you are unlucky with hardware, it will already have users and disk speeds, and network speeds may not be the most comfortable (and we are talking only about official runpod partners, not the community.

maybe it makes sense to make a stripped down version of the image for mode `WORKSPACE_SYNC=true`.
what do you think about that?

**Comment by robballantyne** [comment]
It can be done by extending the base image so it has all of the startup scripts of the ComfyUI image but without actually doing the install step.

It's feasible, but I'm very busy with many projects and I don't have time to dedicate to it currently.  It would be better to petition RunPod to cache the image to prevent long waiting times
