### ISSUE TITLE
how to download file to docker when it's running?

### ISSUE THREAD

**Issue by HamiguaLu** [ai-dock/comfyui#62]
Hi there,  just start my first instance on vast.ai
So sorry if the question seems silly

I just want to download the model and loras from web
But doesn't work out well
 
For example when I try with curl to download a zip file from dropbox, it gives me "unknow host" error

Not sure it's a limiation of image or network issue

Thanks in advance

**Comment by robballantyne** [comment]
Unknown host sounds like DNS problems with the host machine.  You shouldn't experience that at all.

It should be straightforward to curl/wget any file.  Can you try another machine and let me know if it's still failing?

**Comment by HamiguaLu** [comment]
@robballantyne Thanks for the hint ,  works on my server, so it's a network issue
