### ISSUE TITLE
How to connect to comfyui websocket endpoint

### ISSUE THREAD

**Issue by HamiguaLu** [ai-dock/comfyui#63]
Hi
I have encoutered a issue,  can not connect to comfyui ws endpoint,  I can load the web UI, but with ws, it returns some thing to ask me usr/pwd info

So just wonder if disable WEB_ENABLE_AUTH can work ?

**Comment by HamiguaLu** [comment]
Hi, set WEB_ENABLE_AUTH = false doesn't work

**Comment by robballantyne** [comment]
Don't add spaces
