### ISSUE TITLE
Custom nodes, imports fails. Moving mamba env to workspace?

### ISSUE THREAD

**Issue by dkampien** [ai-dock/comfyui#68]
I installed some custom nodes but they keep getting import failed. I think this is due to the mambe env not being persistent in the workspace folder. You mentioned in the base image docks something about moving the env to workspace and that it's the default to true. But I can't find the env in workspace. Do I need to do something specific?

**Comment by robballantyne** [comment]
Which nodes? Can you provide a log?

Persisting the environment is only useful if you want the node dependencies to remain installed after the container has been removed. It's not usually necessary as nodes will have their dependencies installed on ComfyUI start.

I need to update the documentation because the default is now `WORKSPACE_MAMBA_SYNC=false` (also supports using old var `WORKSPACE_SYNC`)

If you set that variable to `true` the micromamba environments will be moved from `/opt/micromamba` to `/workspace/environments/` but I don't think it'll fix whatever is causing the import failure

**Comment by dkampien** [comment]
Yes that is exactly what I want. For my environment to be persistent after the container has been removed. 

I imagine installing many custom nodes and dependencies at ComfyUI start would take some time. By the way, Im using the template from Runpod.io and the image pull everytime I want to use it is very slow. About 40 mins for the 4.8GB. Any solution for this? 

I will try and find a log and come back.

**Comment by dkampien** [comment]
@robballantyne

**Comment by jgal14** [comment]
@dkampien did you ever find a solution for this custom node installation failure?

**Comment by dougbtv** [comment]
Running into the same issue... for example:

```

2024-05-08T22:32:19.176400003Z Traceback (most recent call last):
2024-05-08T22:32:19.176401343Z   File "/workspace/ComfyUI/nodes.py", line 1864, in load_custom_node
2024-05-08T22:32:19.176402693Z     module_spec.loader.exec_module(module)
2024-05-08T22:32:19.176403943Z   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2024-05-08T22:32:19.176405373Z   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2024-05-08T22:32:19.176406803Z   File "/workspace/ComfyUI/custom_nodes/comfy-image-saver/__init__.py", line 1, in <module>
2024-05-08T22:32:19.176408113Z     from .nodes import NODE_CLASS_MAPPINGS
2024-05-08T22:32:19.176409353Z   File "/workspace/ComfyUI/custom_nodes/comfy-image-saver/nodes.py", line 5, in <module>
2024-05-08T22:32:19.176410673Z     import piexif
2024-05-08T22:32:19.176412203Z ModuleNotFoundError: No module named 'piexif'
2024-05-08T22:32:19.176413473Z 
2024-05-08T22:32:19.176414693Z Cannot import /workspace/ComfyUI/custom_nodes/comfy-image-saver module for custom nodes: No module named 'piexif'
2024-05-08T22:32:19.176421263Z Traceback (most recent call last):
2024-05-08T22:32:19.176422563Z   File "/workspace/ComfyUI/nodes.py", line 1864, in load_custom_node
2024-05-08T22:32:19.176423823Z     module_spec.loader.exec_module(module)
2024-05-08T22:32:19.176425093Z   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2024-05-08T22:32:19.176427583Z   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2024-05-08T22:32:19.176429573Z   File "/workspace/ComfyUI/custom_nodes/was-node-suite-comfyui/__init__.py", line 1, in <module>
2024-05-08T22:32:19.176431113Z     from .WAS_Node_Suite import NODE_CLASS_MAPPINGS
2024-05-08T22:32:19.176432423Z   File "/workspace/ComfyUI/custom_nodes/was-node-suite-comfyui/WAS_Node_Suite.py", line 37, in <module>
2024-05-08T22:32:19.176433683Z     from numba import jit
2024-05-08T22:32:19.176434953Z ModuleNotFoundError: No module named 'numba'
```

I can work around it temporarily by using the "install pip packages" from the manager UI node, but... currently looking into doing something to work around this in the meanwhile to make it persistent

**Comment by robballantyne** [comment]
Theres a bug with the default provisioning script. It should run an install for all declared nodes, but it won't unless AUTO_UPDATE is enabled.  I'll fix this asap - I can also extend the behaviour to install requirements for all nodes which seems sensible. 

Should be able to do this within 24 hours

**Comment by dougbtv** [comment]
I tried my hand at it in #73 -- feedback welcome, or, if you were thinking of something else feel free to close/replace it. (I'm still in the process of testing it...)

**Comment by dougbtv** [comment]
@dkampien , re: 

> By the way, Im using the template from Runpod.io and the image pull everytime I want to use it is very slow. About 40 mins for the 4.8GB. Any solution for this?

I think 4.8 gig is actually a "not too bad" of a filesize for this kind of app, I've struggled to get a1111 and kohya builds down to this size.

In some cases, it might be runpod (and/or the image registry?), I also have times where the image pull takes forever randomly.

**Comment by benlau** [comment]
> Theres a bug with the default provisioning script. It should run an install for all declared nodes, but it won't unless AUTO_UPDATE is enabled. I'll fix this asap - I can also extend the behaviour to install requirements for all nodes which seems sensible.
> 
> Should be able to do this within 24 hours

I am curious; is it fixed? Seem that it is still not reinstalling the packages . I need to write a provisioning script to make it works. (running in runpod)

**Comment by robballantyne** [comment]
Unfortunately not. There have been very few updates pushed actually but there will be a big update in the next few days hopefully that will alleviate this problem along with other small issues.  I'm removing micromamba and moving everything to venv.

Remember, the provisioning script is just a bash script and it can be written in any style. You can just use a list of commands as you'd write them into a terminal if you'd like.  The default script was only ever meant as an example, but it will definitely be fixed when my update is ready

**Comment by benlau** [comment]
got it. thx

By the way, out of curiosity, what is the reason to drop micromamba?

**Comment by robballantyne** [comment]
It causes more issues than it solves:

- No ROCm distribution of PyTorch
- Installing jupyter (nodejs dependency) breaks nano editor
- Pulls system libraries from untrusted source (forge)
- Pulled system libraries are occasionally broken

I like micromamba and outside of containers it's still my go-to, but my new solution is cleaner, leaner and less likely to give me a future headache - I hope!

**Comment by d3mi3n** [comment]
@robballantyne maybe I'm missing something, in my case I'm running mostly on serverless and reinstallnig pyhthon dependencines every time seems like a waste of time. As an example I'm using `ComfyUI-AutomaticCFG` and this custom node requires `colorama` to work. 

I've looked through the codebase and from what I could tell both `micromamba` and the new `venv` implemenataion would store everything under the `/opt` folder. Is there a reason why we can't have that folder under the `/workspace`?

My experience with python and docker is quite limited, so appoligies in advance if I'm asking silly questions.

**Comment by robballantyne** [comment]
@benlau New method to sync environment:

```
venv-sync comfyui
```

Run it manually whenever it's convenient to backup your container environment to a persistent disk

**Comment by av** [comment]
Thanks for providing means to sync the env!

It looks like it can't be re-run, however, as `$workspace_path` would be present after the first sync

**Comment by robballantyne** [comment]
> Thanks for providing means to sync the env!
> 
> It looks like it can't be re-run, however, as `$workspace_path` would be present after the first sync

No you can't re-run it, but I am not sure why you would want to.

If you're using the same docker image for each run then you'd only be moving the same files and potentially overwriting any modifications you wanted to keep.  If you're using a more recent image then you probably break version control - My view is that once you take the environment out of the container then you need to manage updates manually, although `AUTO_UPDATE=true` should still function correctly 

You can delete the workspace env and then re-run for a clean start though
