### ISSUE TITLE
Is comfyui:pytorch-2.1.0-py3.11-cuda-12.1.0-base-22.04  available❓

### ISSUE THREAD

**Issue by SoaringTiger** [ai-dock/comfyui#7]
## Thank you for your great work!  
I am using ghcr.io/ai-dock/comfyui:pytorch-2.0.1-py3.10-cuda-11.8.0-base-22.04 now.
### It saved me a lot of time ⌚️
I  note that pytorch:2.1.0-py3.11-cuda-12.1.0-base-22.04  is available.
and I try to download ghcr.io/ai-dockcomfyui:pytorch-2.1.0-py3.11-cuda-12.1.0-base-22.04
but got error: Error response from daemon: manifest unknown

**Comment by robballantyne** [comment]
Really pleased that you're getting good use from this, @SoaringTiger 

I haven't yet built for that target - Only because I've been making lots of changes to the underlying images (base) to enable use as a serverless worker.

As soon as that's done I'll build more - won't be long!

**Comment by robballantyne** [comment]
2.1.1+cu12.1/12.2 is now available

**Comment by SoaringTiger** [comment]
> 2.1.1+cu12.1/12.2 is now available

I have pulled comfyui:pytorch-2.1.1-py3.10-cuda-12.2.0-base-22.04

got error: 
'''
==> /var/log/supervisor/supervisor.log <==
Starting ComfyUI...
/opt/ai-dock/bin/supervisor-comfyui.sh: line 77: micromamba: command not found

==> /var/log/supervisor/supervisor.log <==
INFO spawned: 'comfyui' with pid 340
INFO exited: comfyui (exit status 127; not expected)
INFO gave up: comfyui entered FATAL state, too many start retries too quickly
'''

After switch to latest comfyui:pytorch-2.0.1-py3.10-cuda-11.8.0-base-22.04

**Comment by robballantyne** [comment]
Apologies. 12.2 will be deleted as it doesn't work. 12.1 should be ok

**Comment by SoaringTiger** [comment]
> Apologies. 12.2 will be deleted as it doesn't work. 12.1 should be ok

I have pulled 
comfyui:pytorch-2.1.1-py3.10-cuda-12.1.0-base-22.04
and 
comfyui:pytorch-2.1.1-py3.10-cuda-11.8.0-base-22.04

run test

```
/opt/ai-dock/tests# python assert-torch-version.py
Expected pytorch v2.1.1 but found v2.0.1
```

**Comment by robballantyne** [comment]
I have pulled the same images and the PyTorch version is correct (exit 0, no output)

```
CONTAINER ID   IMAGE                                                                 COMMAND     CREATED         STATUS         PORTS                                                                                                                    NAMES
9031d02d9136   ghcr.io/ai-dock/comfyui:pytorch-2.1.1-py3.10-cuda-12.1.0-base-22.04   "init.sh"   9 seconds ago   Up 5 seconds   0.0.0.0:1111->1111/tcp, 0.0.0.0:8188->8188/tcp, 0.0.0.0:8888->8888/tcp, 0.0.0.0:53682->53682/tcp, 0.0.0.0:2222->22/tcp   comfyui-supervisor-1
rob@Veriton-Router:~/ai-dock/comfyui$ dcx
(comfyui) root@9031d02d9136:/workspace# python /opt/ai-dock/tests/assert-torch-version.py (comfyui) root@9031d02d9136:/workspace#
```
That script is executed at build time and will break the automated builds if the PyTorch version is incorrect.

Do you have a node being installed that could be interfering with the torch version?

**Comment by robballantyne** [comment]
@SoaringTiger Just had a thought. The way the image is designed, if you pull a new image but have an existing synced workspace, the environment will not be affected.  

This is by design to allow you to receive base security or feature enhancements without breaking a working install.

I think in this case you'll need to delete your workspace/environments directory and re-launch

**Comment by SoaringTiger** [comment]
> @SoaringTiger Just had a thought. The way the image is designed, if you pull a new image but have an existing synced workspace, the environment will not be affected.
> 
> This is by design to allow you to receive base security or feature enhancements without breaking a working install.
> 
> I think in this case you'll need to delete your workspace/environments directory and re-launch

I made a new directory and everything worked fine afterwards. 👍

**Comment by SoaringTiger** [comment]
> @SoaringTiger Just had a thought. The way the image is designed, if you pull a new image but have an existing synced workspace, the environment will not be affected.
> 
> This is by design to allow you to receive base security or feature enhancements without breaking a working install.
> 
> I think in this case you'll need to delete your workspace/environments directory and re-launch

I made a new directory and everything worked fine afterwards. 👍
