### ISSUE TITLE
Getting error "value_not_in_list", i.e. checkpoint is not getting loaded somehow.

### ISSUE THREAD

**Issue by abhinavzspace** [ai-dock/comfyui#75]
It got successfully deployed to runpod serverless. I followed the instructions given.

Template looks like:

![Screenshot 2024-05-16 143620](https://github.com/ai-dock/comfyui/assets/6252284/21209bf5-8b22-470e-aad4-a186a8ffd156)

[Payload used](https://github.com/ai-dock/comfyui/blob/main/build/COPY_ROOT/opt/serverless/docs/example_payloads/raw_text2image.json)

The error I am getting:
`
"error": "{'4': {'errors': [{'type': 'value_not_in_list', 'message': 'Value not in list', 'details': \"ckpt_name: 'v1-5-pruned-emaonly.ckpt' not in []\", 'extra_info': {'input_name': 'ckpt_name', 'input_config': [[]], 'received_value': 'v1-5-pruned-emaonly.ckpt'}}], 'dependent_outputs': ['9'], 'class_type': 'CheckpointLoaderSimple'}}",
`

I know I must be missing something basic. Any help highly appreciated.

**Comment by robballantyne** [comment]
It's best to avoid using the latest tag as breaking changes are coming soon.

Also, the docker image doesn't contain any images so you'll need to either build a custom images with models included (best option imo) or run first on a pod instance with `WORKSPACE_MAMBA_SYNC=true` to configure your network volume. Your serverless workers should then use the same variable but using volumes is slow on RP

**Comment by abhinavzspace** [comment]
I built the image manually while providing [PROVISIONING_SCRIPT](https://pastebin.com/raw/9CtWhvHc). Still I am facing the same issue.

My steps are:

1. Forked and cloned the project locally to my WSL2 in windows.
2. Added a .env file with PROVISIONING_SCRIPT and AUTO_UPDATE=true.
3. Built the image and pushed to my docker hub.
4. Use my personal image:tag in runpod.

Could WSL2 be the issue?

**Comment by robballantyne** [comment]
No, I don't think so.

The issue comes from ComfyUI being unable to find the model.  You should store it in the network drive at /runpod-volume/storage/stable_diffusion/checkpoints/{model name} and it should work properly.

I am going to update the docs for this because they're not very helpful and it can be confusing. Sorry for that

**Comment by abhinavzspace** [comment]
Sorry, but I am a bit confused.

We have to store the model in network drive even if we provide PROVISIONING_SCRIPT? I thought that the script downloads the model from huggingface or civitai by its own?

**Comment by robballantyne** [comment]
Yes, the provisioning script won't run in serverless because you'd waste a lot of GPU time at idle while waiting for downloads

**Comment by abhinavzspace** [comment]
Hmm. I guess serverless mode is not good, when quick response needed anyway. Thank you!
