### ISSUE TITLE
endpoint.run not working

### ISSUE THREAD

**Issue by erwinlukem** [ai-dock/comfyui#78]
no problem when using endpoint.runsyc but when I use endpoint.run its always failing. im getting "error": "Server not ready after timeout (30s)" or "error": "Failed to queue job". Thank you rob! awesome work!

**Comment by robballantyne** [comment]
I'm working on some fundamental changes to the startup routine which will hopefully eradicate timeout errors.

It may take a couple of weeks to get all finished with proper testing but making this work efficiently is high priority

**Comment by erwinlukem** [comment]
Thank you!

**Comment by robballantyne** [comment]
No longer including RunPod handlers in latest builds. New API wrapper will work anywhere but will require users own handler's.  Instructions to be updated in due course
