### ISSUE TITLE
How to Setup serverless with custom nodes and models

### ISSUE THREAD

**Issue by NitinGCJ** [ai-dock/comfyui#80]
Can anyone explain the detailed steps to build the docker image which includes custom ComfyUI nodes and models like IP-adpater/ controlnet?

**Comment by twinnedAI** [comment]
@NitinGCJ one way would be to customise the docker build in:
**build/COPY_ROOT_EXTRA/opt/ai-dock/bin/build/layer1/init.sh**
just uncomment this part (line 11) to:

```
NODES=(
    "https://github.com/ltdrdata/ComfyUI-Manager"
)

```

**Comment by robballantyne** [comment]
Above is correct. Future updates will not include cloud provider specific handlers for serverless but will include a built in API wrapper to use instead.  Instructions will be updated accordingly and old builds will be unaffected
