### ISSUE TITLE
How Can I link with Krita AI Plugin

### ISSUE THREAD

**Issue by tathaha** [ai-dock/comfyui#85]
How Can I link the Krita ai plugin to Cloud GPU on vast.ai Instances because it just routes to /login again and again

**Comment by robballantyne** [comment]
Does Krita plugin support auth? Really it should otherwise you'll need to add environment variable `WEB_ENABLE_AUTH=false`

Naturally this is not secure over the internet.

**Comment by tathaha** [comment]
Thank it work now ❤️
