### ISSUE TITLE
DeepFuze node on comfy ui. 

### ISSUE THREAD

**Issue by mogupta** [ai-dock/comfyui#93]
Hi Please let us know if you can help. 
https://github.com/SamKhoze/ComfyUI-DeepFuze/issues/44

**Comment by mogupta** [comment]
![image](https://github.com/user-attachments/assets/a40c779b-dce6-4fb0-80f2-41de512113e4)

using cuda 11.8  but still getting 12.x

**Comment by robballantyne** [comment]
That's just the maximum supported version of CUDA supported by your driver

You can still run the cu118 version there if you need to
