### ISSUE TITLE
Bypass ai-dock authentication for api requests to Comfy (runpod)

### ISSUE THREAD

**Issue by baeuke** [ai-dock/comfyui#95]
Hi,
When making an API request to a runpod instance running Comfy, the request first redirects to an ai-dock webpage for authentication. Is there a way to include the credentials directly in the API request to bypass this step and access Comfy without manual authentication?
Thank you.

**Comment by robballantyne** [comment]
You need an Authorization header 

`Authorization: Bearer $WEB_TOKEN`

The variable is auto generated if you haven't explicitly set it

**Comment by baeuke** [comment]
How do we explicitly set the token?
by adding an environment variable when editing ai-dock template in runpod?

**Comment by robballantyne** [comment]
Yes, it's the equivalent of providing the docker run argument `-e WEB_TOKEN=mysecret`

**Comment by baeuke** [comment]
Thank you @robballantyne, works!

**Comment by bollerdominik** [comment]
Hi @robballantyne this works fine (thanks!) but it would be great if it is documented somewhere. Maybe I missed it in the doc but WEB_TOKEN is not described anywhere.

**Comment by robballantyne** [comment]
@bollerdominik You're right, I'll fix that asap. Docs really need an overhaul
