### ISSUE TITLE
Newbie question on usage

### ISSUE THREAD

**Issue by dgwyer** [ai-dock/comfyui#96]
Pretty new to vast.ai and not that experienced with containers. Can I just clarify how to use this on vast.ai? Do I just enter create a new template on vast.ai and enter the GitHub URL of th a-dock/comfyui repository, and set the rest of the options in the vast.ai template web form?

Or is there more to it than that? I read the readme but there wasn't a section for total idiots like me. :)

**Comment by robballantyne** [comment]
There's no need to create a brand new template. You can follow the link at the bottom of the readme. It leads to a pre configured vast template - You can edit it as you need as it will save a new version
