### ISSUE TITLE
flux support?

### ISSUE THREAD

**Issue by fahadshery** [ai-dock/comfyui#98]
Hi,

I am currently using https://github.com/AbdBarho/stable-diffusion-webui-docker

That doesn't have flux support because I get the error of not being able to load the model.

Have you tested flux?

Cheers

**Comment by robballantyne** [comment]
Hi @fahadshery ,

Flux is supported and working well and tested on vast-ai (see the link at the bottom of REAMD.md to test)

**Comment by jozi** [comment]
i test this link https://link.ai-dock.org/template-vast-comfyui-flux
and on comfyui dont load flux

**Comment by robballantyne** [comment]
Hi

I have seen this too.  ComfyUI loads it's default workflow differently in recent versions so I'm looking for a fix

Right now the best thing to do is download a flux workflow to your local pc and load it in the ComfyUI interface
